version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      java: corretto8
  pre_build:
    commands:
      - echo "Entered the ore-build phase"
      - $( aws ecr get-login --no-include-email --region $AWS_REGION)
      - java -version
      - mvn -vesion
  build:
    commands:
      - echo "Entered build phase"
      - cd authorization-service
      - mvn clean install
      - echo "Building docker image"
      - docker build -t authorizationservice:latest .
      - docker tag authorizationservice:latest 690236230744.dkr.ecr.us-east-2.amazonaws.com/pod4-authservice:authorization-service
  post_build:
    commands:
      - echo "Entered post build phase"
      - docker push 690236230744.dkr.ecr.us-east-2.amazonaws.com/pod4-authservice:authorization-service
      - printf '[{"name":"authorizationservice-container", "imageUri":"%s"}]' 690236230744.dkr.ecr.us-east-2.amazonaws.com/pod4-authservice:authorization-service > taskdefinition.json
artifacts:
  files:
    - authorization-service/taskdefinition.json